// Generated by CoffeeScript 1.6.3
(function() {
  var DEFAULT_EXTENSIONS, url;

  url = require('url');

  DEFAULT_EXTENSIONS = {
    '.json': 'application/json',
    '.html': 'text/html',
    '.txt': 'text/plain',
    '.xml': 'application/xml'
  };

  module.exports = function(exts) {
    if (exts == null) {
      exts = DEFAULT_EXTENSIONS;
    }
    return function(req, res, next) {
      var content_type, ext, parts;
      parts = url.parse(req.url);
      for (ext in exts) {
        content_type = exts[ext];
        if (!(parts.pathname.slice(-ext.length) === ext)) {
          continue;
        }
        parts.pathname = parts.pathname.slice(0, -ext.length);
        req.url = url.format(parts);
        req.headers.accept = content_type;
        break;
      }
      return next();
    };
  };

}).call(this);
